name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        build_type: [shared]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson==1.4.0 ninja
      - name: Compile bcdec (msvc)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64
          meson setup . build/ --buildtype release --prefix ${{ github.workspace }}/artifact/ -Ddefault_library=${{ matrix.build_type }} --optimization 3
          meson compile -C build
          meson install -C build
      - name: Compile bcdec (other)
        if: matrix.os != 'windows-latest'
        run: |
          meson setup . build/ --buildtype release --prefix ${{ github.workspace }}/artifact/ -Ddefault_library=${{ matrix.build_type }} --optimization 3
          meson compile -C build
          meson install -C build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.build_type }}
          path: ${{ github.workspace }}/artifact